#+TITLE: Related Work

* A Generator for Type Checkers by H. Gast
* Formally Specified Type Checkers for Domain Specific Languages: Experience Report by van den Brand, van der Meer, Serebrenik, Hofkamp
  - Designed for the quick prototyping of the specification language
    Chi 2.0, a language for describing concurrent systems.
  - Well integrated in the Chi tool-chain.
  - Typing rules are described in the MSDF format that describes
    typing rules in transition like format. One advantage is that
    cntext information are only mentioned when needed. This is great
    for extensibility and modularity.
  - MSDF also features module structures and imports. Judgments and
    related stuff are defined implicitly using the transition system.
  - MSDF is translated to Pyke. Originally Pyton was chosen as target,
    but Python does not feature backtracking capabilties by default
    (for cases in which more than one rule is applicable). Pyke has
    this feature and is inspired by Prolog (it uses the concet of
    backwardchaining rules).
  - The transformation form MSDF to Pyke is done with ASD+SDF.
  - The authors noticed that the integration in the Chi tool-chain
    required specific knowlege about the AST/DAST, thus protability to
    other languages is difficult.
  - The authors also have an interesting perspective on type systems
    as state machines.
* Programmable Type Systems for Domain Specific Languages by Peter Thiemann
  - The type system of Haskell is extended to ensure the correct generation of HTML
  - They employ a first-order functional logic programming language at type level to express domain specific concepts
* Semantics of Programming Languages: A Tool-oriented Approach by Heering, Jan and Klint, Paul
  - Observation: The fields semantics, tools and languages drifting
    further apart.
  - Reason: Semantics are rarely incooperated into pratical systems
    and hence do not influence tools and (partly) languages.
  - Solution: Generate as many language-based tools as possible form a
    semantic definition. The authors provide a hughe list of tools
    that could possibly be generated. Currently only generators for
    parsers and lexers are widely used. The authors have the vision of
    a development workbench for languages that can be used to generate
    most tools from a semantic definition.
  - Existing generation tools that can generate type checkers are
    + Synthesizer Generator
    + PSG
    + ASF+SDF
    + Centaur
    + Gem-Mex
  - Other tools that could potentially generate type checkers
    + SIS
    + DSP
    + GAG
    + SPS
    + MESS
    + Actress
    + Pregmatic
    + LDL
    + Eli
* Should Your Specification Language Be Typed? by Lamport, Paulson
* A Formal Description of a Type Checking Algorithm by Naeem, Harrison
  - Formal description of a type checker of a object oriented programming language called POOL.
  - POOL: class-based strongly typed object oriented programming language with parametric types
  - Type checking done bottom-up
  - Computing least common type for assignments
* Ott: Effective tool support for the working semanticist by Swell, Nardelli, Owens, Peskine, Ridge, Sarkar, Strniska
  - Designed a meta-language to faciliate development of languages
  - This meta-language aims at concise and definitions that are easy to read/edit
  - Meta-language is divided into two languages, one is specifically desinged to describe binding constructs
  - Meta-language is compiled to proof-assistent and latex code
* Automatic Generation of Object-Oriented Type Checkers
* [#C] Strict Bidirectional Type Checking
  - Does not seem that helpfule.
  - Look into it if I have time left, or no other ideas.
* [#A] Checking Algorithms for Pure Type Systems
  - This can be interesting!
  - They do not do this automatically, but the reasoning might be interessting.
* [#A] Automatic Type Inference via Partial Evaluation
  - Very interesting and closely related to my work
