%% Pretty printer for first-order formulas in the TPTP format.
[
    FOFGoal__ -- V [ _1 _ 2],
	FOFGoal__ -- V [ _1 _2 _3 ],
	Formula__ -- H hs=0 ["fof('" _1 "', " _2 ", " _3 ")."],
	Axiom__ -- "axiom",
	Conjecture__ -- "conjecture",
	All__ -- "(![" _1 "] : " _2 ")",
	All__.1:iter-star-sep -- _1 ", ",
	Exists__ -- "(?[" _1 "] : " _2 ")",
    Exists__.1:iter-star-sep -- _1 ", ",
    Neq__ -- "(" _1 " != " _2 ")",
    Eq__ -- "(" _1 " = " _2 ")",
	Impl__ -- "(" _1 " => " _2 ")",
	Impl__.1:iter-star-sep -- _1 " & ",
	And__ -- "(" _1 ")",
	And__.1:iter-star-sep -- _1 " & ",
	And__ -- "(" _1 " & " _2 ")",
	Or__ -- "(" _1 ")",
	Or__.1:iter-star-sep -- _1 " | ",
	Or__ -- "(" _1 " | " _2  ")",
	True__ -- "$true",
	False__ -- "$false",
	Var__ -- _1,
	Pred__ -- _1,
	Pred__ -- _1 "(" _2 ")",
	Pred__.2:iter-star-sep -- _1 ", ",
	Term__ -- _1,
	Term__ -- _1 "(" _2 ")",
	Term__.2:iter-star-sep -- _1 ", "	
]